import NextAuthProvider from "@/components/layout/NextAuthProvider";
import "./globals.css";
import NavBar from "@/components/layout/NavBar";
import Footer from "@/components/layout/Footer";

export const metadata = {
  title: "Viola | ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <NextAuthProvider>
          <NavBar />
          {children}
          <Footer />
        </NextAuthProvider>
      </body>
    </html>
  );
}
